"""add_play_count_to_tracks

Revision ID: 38d216f3b7c8
Revises: e4228fc45e1f
Create Date: 2025-11-24 15:16:12.883720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d216f3b7c8'
down_revision: Union[str, Sequence[str], None] = 'e4228fc45e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_deleted_at'), 'albums', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_albums_name'), 'albums', ['name'], unique=False)
    op.add_column('tracks', sa.Column('play_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tracks_created_at'), 'tracks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracks_deleted_at'), 'tracks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tracks_genre'), 'tracks', ['genre'], unique=False)
    op.create_index(op.f('ix_tracks_play_count'), 'tracks', ['play_count'], unique=False)
    op.create_index(op.f('ix_tracks_year'), 'tracks', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_year'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_play_count'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_genre'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_deleted_at'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_created_at'), table_name='tracks')
    op.drop_column('tracks', 'play_count')
    op.drop_index(op.f('ix_albums_name'), table_name='albums')
    op.drop_index(op.f('ix_albums_deleted_at'), table_name='albums')
    # ### end Alembic commands ###
